apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: db
  namespace: zabbix
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-server
  selector:
    name: mysql-server
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10051
    targetPort: 10051
    protocol: TCP
    name: zabbix-trapper
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: snmp-trap
  selector:
    name: zabbix-server
  sessionAffinity: None
  type: ClusterIP 
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 10050
    targetPort: 10050
    name: zabbix-agent
  selector:
    name: zabbix-agent